-- zdatos.sql: poblar tabla Usuario con 30 registros
INSERT INTO Usuario (nombre, correo, fecha_registro, tipo_usuario) VALUES
  ('Ana Gómez',    'ana.gomez@example.com',    CURRENT_DATE, 'comprador'),
  ('Bruno López',  'bruno.lopez@example.com',  CURRENT_DATE - INTERVAL '1 day', 'vendedor'),
  ('Carla Díaz',   'carla.diaz@example.com',   CURRENT_DATE - INTERVAL '2 day', 'comprador'),
  ('David Pérez',  'david.perez@example.com',  CURRENT_DATE - INTERVAL '3 day', 'admin'),
  ('Elena Ruiz',   'elena.ruiz@example.com',   CURRENT_DATE - INTERVAL '4 day', 'vendedor'),
  ('Fabián Ortiz', 'fabian.ortiz@example.com', CURRENT_DATE - INTERVAL '5 day', 'comprador'),
  ('Gabriela Vega','gabriela.vega@example.com',CURRENT_DATE - INTERVAL '6 day', 'vendedor'),
  ('Hugo Castro',  'hugo.castro@example.com',  CURRENT_DATE - INTERVAL '7 day', 'comprador'),
  ('Isabel Torres','isabel.torres@example.com',CURRENT_DATE - INTERVAL '8 day','admin'),
  ('Javier Solis', 'javier.solis@example.com', CURRENT_DATE - INTERVAL '9 day', 'comprador'),
  ('Karla Medina', 'karla.medina@example.com', CURRENT_DATE - INTERVAL '10 day','vendedor'),
  ('Luis Moreno',  'luis.moreno@example.com',  CURRENT_DATE - INTERVAL '11 day','comprador'),
  ('María Peña',   'maria.pena@example.com',   CURRENT_DATE - INTERVAL '12 day','vendedor'),
  ('Norberto Cruz','norberto.cruz@example.com',CURRENT_DATE - INTERVAL '13 day','comprador'),
  ('Olga Santos',  'olga.santos@example.com',  CURRENT_DATE - INTERVAL '14 day','admin'),
  ('Pablo Suárez', 'pablo.suarez@example.com', CURRENT_DATE - INTERVAL '15 day','comprador'),
  ('Queralt Ruiz', 'queralt.ruiz@example.com', CURRENT_DATE - INTERVAL '16 day','vendedor'),
  ('Raúl Mendoza', 'raul.mendoza@example.com', CURRENT_DATE - INTERVAL '17 day','comprador'),
  ('Sofía Blanco', 'sofia.blanco@example.com', CURRENT_DATE - INTERVAL '18 day','vendedor'),
  ('Tomás Bravo',  'tomas.bravo@example.com',  CURRENT_DATE - INTERVAL '19 day','comprador'),
  ('Úrsula León',  'ursula.leon@example.com',  CURRENT_DATE - INTERVAL '20 day','admin'),
  ('Víctor Rojas', 'victor.rojas@example.com', CURRENT_DATE - INTERVAL '21 day','comprador'),
  ('Wendy Silva',  'wendy.silva@example.com',  CURRENT_DATE - INTERVAL '22 day','vendedor'),
  ('Ximena Paz',   'ximena.paz@example.com',   CURRENT_DATE - INTERVAL '23 day','comprador'),
  ('Yahir Reyes',  'yahir.reyes@example.com',  CURRENT_DATE - INTERVAL '24 day','vendedor'),
  ('Zulema Avila', 'zulema.avila@example.com', CURRENT_DATE - INTERVAL '25 day','comprador'),
  ('Alan Núñez',   'alan.nunez@example.com',   CURRENT_DATE - INTERVAL '26 day','vendedor'),
  ('Beatriz Sol',  'beatriz.sol@example.com',  CURRENT_DATE - INTERVAL '27 day','comprador'),
  ('Cristina Paz', 'cristina.paz@example.com', CURRENT_DATE - INTERVAL '28 day','vendedor'),
  ('Diego Varela', 'diego.varela@example.com', CURRENT_DATE - INTERVAL '29 day','comprador');